### ISSUE TITLE
constant nonzero background and excess CSF

### ISSUE THREAD

**Issue by maarten-naeyaert** [DevelopmentalImagingMCRI/mantis#7]
Dear all,

I've noticed that sometimes there are segments which have a non-zero background, which is somewhat inconvenient but can be removed with a few lines of code. 
However, if the CSF segment is affected, there is an outer rim of CSF which is difficult to distinguish from the actual CSF. The rim is not present in the 'hard' atlas.
The input for the segmentation were skull-stripped using the tool provided with MANTiS, which seemed to work well in these cases. 
The screenshot shows the c3 component with nonzero background and CSF rim in white, with the (correct) 3rd component of the 'hard' segmentation overlaid in green. (The bright white are the cerebellum etc. of the other components of the hard atlas)

![image](https://user-images.githubusercontent.com/52161475/60017071-36c35380-9688-11e9-936d-6963573ddfe7.png)

Is it known what causes this problem? And how it can be solved?

thanks in advance!
best regards,
Maarten

**Comment by richardbeare** [comment]
Thanks for the report.

I haven't seen this behaviour before. I would speculate that perhaps the size of the brain in the problem images is dramatically different from the template, or that the reoriented image has been padded with values that are sufficiently different to the rest of the background and thus cause problems with steps that use histograms to estimate thresholds.

My first thought would be to process the original scan without a reorientation + resample step (assuming you have access to it). Reorientation without resampling should work.

We'd need to get copies of the data to debug any further.

**Comment by maarten-naeyaert** [comment]
The FoV is considerably larger as the template, but the brain itself is about the same size I would guess. I trimmed off the excess FoV so there would be less or no padding, and only did the watershed scalping a COM correction without a rotation to reduce the chance for resampling issues, but the problem persists, so it doesn't seem to be related immediately. (I made sure to use a subject that was already oriented quite well by itself)

I could send you data, albeit only next week. Do you have a secure channel?

**Comment by richardbeare** [comment]
I can send an upload token - what is your preferred email.

**Comment by maarten-naeyaert** [comment]
that would be maarten.naeyaert@uzbrussel.be 
Sorry for the late answer, but I can send the data today.

**Comment by richardbeare** [comment]
Hi,
I've had a look into this. The nonzero background CSF appears to be something we've introduced in phase 2. Not sure how. I think we use the scalped brain as a mask to discard those areas before doing hard segmentation.
I don't think this is the cause of the clipping at the brain edge, as the phase 1 results exhibit the clipping but not the nonzero background.

I suspect the issue is insufficient flexibility in the affine registration step, which means the long, narrow,  brain (AGFA2232742) is never able to be properly aligned to the template. The spm tissue classification does offer some choices of affine regularization, but we don't have a way of accessing them from mantis. I experimented with some, but it didn't change anything. There's no guidance I can find on setting up the regularization parameters for that step.

Your best bet may be to apply a transformation to make the shape more typical (eg via the check registration option - scale in the x direction) and revert it afterwards. Unfortunately this will probably mean you need to align the center line with the y and z axis as well (i.e roll and yaw).

You may be able to avoid some of the manual steps by co-registering problem brains to ones that work - whether this is a worthwhile approach will depend on the number of problem subjects. The brain masks may also provide a useful cue in estimating the affine transform.
